[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성 (a <= x < b)
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [ ]:
import numpy as np
np.random.randint(1,3)
# numpy randint는 마지막숫자 제외.
# 파이썬 randint는 마지막숫자 포함

In [ ]:
# Python random

import random

print(random.random(),'\n')  # 0.0 <= x < 1.0 사이 랜덤수 출력
print(random.randint(1,10),'\n') # 지정범위 내 랜덤정수 출력 (1 <= x <= 10). numpy  randint와 범위혼동주의
print(random.uniform(10,20),'\n') # 지정 범위(min, max) 내 랜덤 실수(float) 출력
print(random.randrange(10),'\n') # 지정값 내 랜덤정수(int) 리턴\
print(random.choice([1,2,3,4,5]), '\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
print('='*50)
li = [1,2,3,4,5]
print(random.sample(li,3), '\n')  # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴, 셔플값으로 넣은걸 프린트하면 적용된것 확인 가능
print(li)

- 0과 1 사이 균일분포 (rand)

In [ ]:
import random
import numpy as np

r = np.random.rand(6) # 0에서 1사이의 균일분포. 6개를 뽑음.
print(r)
r.mean()

- 표준 정규분포

In [ ]:
r = np.random.randn(10000) # 평균 0 표준편차 1
print(r,'\n')
r.mean()

In [ ]:
np.random.uniform(1.0, 2.0, 10) # 1.0과 2.0 사이의 10개가 나옴
                                # 정수일땐 randint, 실수일땐 uniform 사용하면됨

In [ ]:
np.random.uniform(0,1,(2,3))  # 개수대신 튜플로 묶어서 2행 3열 줌

- np.random.random_sample(행,열)
- 0 ~ 1 사이의 난수 실수값으로 행렬 생성
- uniform 함수의 최소값, 최대값을 0, 1로 지정한 것과 같음

In [ ]:
np.random.random_sample((2,3))     # 그래서 행렬만 줌 

In [ ]:
import pandas as pd
import numpy as np
ar = np.random.rand(4,8)    # rand : 균일분포.  4행 8열
ar

In [ ]:
df = pd.DataFrame(ar)
df
# df = pd.DataFreme(ar, columns = ['id','gender','age','region','product','price','qty','time'])

In [ ]:
# columns 8개에 대한 이름 columns = ['id','gender','age','region','product','price','qty','time']
df.columns = ['id','gender','age','region','product','price','qty','time']
df

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df3을 출력하세요.

In [ ]:
df1 = df[['id','gender','age']]
df2 = df1.copy()
df2.id = np.random.randint(1,100,4)  # 각 값 개별설정방법?
df2.gender = np.random.choice(['male','female'],4)
df2.age = np.random.randint(1,100,4)
df2[['id','gender','age']]

In [ ]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_ar = np.random.randn(100000) # randn : 표준정규분포
large_ar.sort() # np.array에 sort 적용하면 원본에 반영됨

In [ ]:
large_ar[int(0.5*len(large_ar))]

- 배열 집합 연산

In [ ]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names) # 중복 필터링

In [ ]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

In [ ]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])   # i n 1(숫자) d. 2,3,6에 넣은 값이 있으면 그값만 True

- 배열 데이터의 입출력

In [ ]:
ar = np.arange(10)
np.save('some_ar', ar)

In [ ]:
np.load('some_ar.npy')  # 확장자는 npy.

- np.savez : 여러개의 배열을 압축된 형식으로 저장

In [ ]:
np.savez('ar_archive.npz', a=ar, b=ar)

In [ ]:
arch = np.load('ar_archive.npz')
arch['a']

In [ ]:
arch['b']

In [ ]:
a = np.arange(1,10)
print(a, '\n')
np.argsort(a)   # 인덱스 순서 찾는 함수

In [ ]:
# 인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]

###  도전과제(7/6)
- np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [186]:
import numpy as np
a = np.arange(336).reshape(6,7,8)
# reshape(6,7,8)은 3차원 6개가 각각 56개씩 있는것이므로 2번째판,3차원 인덱스1에 100번째 요소가 존재
print(a[1], '\n')
# 줄당 8개씩 있으므로 6째행, 즉 행인덱스 5에 해당하는 곳에 값이 있음(97~104번째 요소)
print(a[1,5])
# 100번째 요소인 99가 있는 마지막 인덱스위치를 써 넣는다.
a[1,5,3]
b = a.reshape(-1) # 1차원으로 바꿔줌
c = np.where(b[99],)

[[ 56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103]
 [104 105 106 107 108 109 110 111]] 

[ 96  97  98  99 100 101 102 103]


NameError: name 'true' is not defined

- np.arange(4)을 이용하여 아래와 같이 출력하세요.

In [187]:
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

NameError: name 'array' is not defined

In [188]:
a = np.arange(4) # np.zeros?
b = a+1
b

array([1, 2, 3, 4])

In [189]:
zero = np.zeros((5,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [190]:
zero[1,0] = b[0]
zero[2,1] = b[1]
zero[3,2] = b[2]
zero[4,3] = b[3]
zero

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

- Q. 0~10 정수 (5,5) 행렬의 역행렬을 구한 후 두 행렬간의 행렬곱을 구하세요.

In [ ]:
ar = np.random.randint(11,size=(5,5))
print(ar,'\n')
ar_r = np.linalg.inv(ar)
print(ar_r,'\n')
ar_d = np.dot(ar,ar_r)
print(ar_d)

# a = np.full((5,5), np.random.randint(0,10))

In [ ]:
# 임의의 행렬과 그 행렬의 역행렬의 곱은 항등열

### 과제(7/6)
-  가이드에 따라서 고객별 연간 구매데이터를 생성하고 아래사항을 수행하세요(관측치 1000개)

- Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

(관측치 1000개)

In [ ]:
거래 번호
- id : 1 ~ 1000번 일련번호 - 개시 후 1000 건의 거래가 있었고 걍 거기에 넘버링한 거라고 이해해보자

고객별 속성 데이터
- cusno : 고객번호 1000개 랜덤   # 겹치지 않는 1000명임(고객별 연간 구매데이터)
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터
- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- price_21 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성
- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21
- sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0

#### Q2. df를 수정하여 3가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요
* 배운거 어떻게든 써서 . . 
* 구매 데이터 생성
* 그룹핑등등 사용
* 피벗으로 잘 됐는지 확인?
#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.
* 분석에는 인덱스를 다른거 뽑아서 사용가능
* 판매율, 고정층, 연령층, 제품가격별, 물량 등등으로 분류해서 확인
* 의미있는 값으로 방향제시 혹은 결과 도출
* 의도한 목표가 잘 됐는지 확인

In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
# 거래 데이터 생성

# 거래 번호
id = pd.Series(random.sample(range(1,1001),1000)) # id arange 사용, (size=)1000
# id_sr , 나머지도 시리즈분리

# 고객별 속성 데이터
cusno = pd.Series(random.sample(range(1,1001),1000)) # 보류. id와같음
gender = pd.Series(np.random.randint(0,2, size = 1000)) # 0과1로바꾸기.이미함
age = pd.Series(np.random.randint(0,81, size = 1000))
region = pd.Series(np.random.randint(1,11, size = 1000))

# 거래 데이터
# id arange ~1001,sample sr 생성
product_20 = pd.Series(np.random.choice([10,20,30])) # 각각 시리즈분리.[식~, for 범위 1000]
product_10 = pd.Series(np.random.choice([10,20,30])) # ,1000

price_20 = pd.Series(np.random.uniform(1000,50000)) # 식 round 반올림2로 감싸주기
price_21 = pd.Series(np.random.uniform(1000,50000)) # ,1000

quantity_20 = pd.Series(np.random.randint(1,101,size=1000))
quantity_21 = pd.Series(np.random.randint(1,101, size=1000))

amount_20 = price_20 * quantity_20
amount_21 = price_21 * quantity_21

sales = amount_21 - amount_20
# 컨캣에는 시리즈 넣어서 만들고 rename으로 열이름 변경
# 데이터프레임만들고 df[열]로 sales, amount 등의 식을 그떄 만들기
# sales는 where로 식만들어서 1,0넣어 치환. c = np.where(a<b, 1, 0)
# 두개 데이터는 join 데이터/ how = outer로 생성 
# df.a = a로 값입력

In [3]:
#df #df.rename으로 column, index 바꿔주기 가능
# 고객별 속성 데이터 : df1
df1 = pd.concat([id, cusno, gender, age, region],axis = 1)
df1.rename(columns={0:'id',1:'cusno',2:'gender',3:'age',4:'region'})

id  cusno  gender  age  region
0    625    807       0   53       8
1    363    288       1    0      10
2    869    982       0   31      10
3    228    479       1   46       9
4    980    851       1   14       3
..   ...    ...     ...  ...     ...
995    1    890       1   72       5
996  971    925       1   59       6
997  536    721       1   28      10
998  929     86       1   58      10
999  803    113       1   42       9

[1000 rows x 5 columns]

In [4]:
# 거래 데이터 : df2
df2 = pd.concat([id, product_20, product_10, price_20, price_21, quantity_20, quantity_21, amount_20, amount_21, sales],axis = 1)
df2.rename(columns = {0:'id', 1:'product_20',2:'product_10',3:'price_20',4:'price_21',5:'quantity_20', 6:'quantity_21',7:'amount_20',8:'amount_21',9:'sales'}, inplace=True)

In [5]:
df2

id  product_20  product_10     price_20      price_21  quantity_20  \
0    625        20.0        30.0  2610.622839  20672.168459           80   
1    363         NaN         NaN          NaN           NaN           18   
2    869         NaN         NaN          NaN           NaN           24   
3    228         NaN         NaN          NaN           NaN           23   
4    980         NaN         NaN          NaN           NaN           62   
..   ...         ...         ...          ...           ...          ...   
995    1         NaN         NaN          NaN           NaN           39   
996  971         NaN         NaN          NaN           NaN           29   
997  536         NaN         NaN          NaN           NaN            2   
998  929         NaN         NaN          NaN           NaN           61   
999  803         NaN         NaN          NaN           NaN           94   

     quantity_21      amount_20      amount_21          sales  
0             47  208849.827158  971591.917564  762742.090406  
1             39            NaN            NaN            NaN  
2             63            NaN            NaN            NaN  
3             17            NaN            NaN            NaN  
4             14            NaN            NaN            NaN  
..           ...            ...            ...            ...  
995           18            NaN            NaN            NaN  
996           39            NaN            NaN            NaN  
997           76            NaN            NaN            NaN  
998           89            NaN            NaN            NaN  
999           95            NaN            NaN            NaN  

[1000 rows x 10 columns]

In [6]:
# 두 데이터프레임 합치기
ddf1 = pd.concat([df1,df2], axis = 1)
ddf1 # 데이터프레임 합침

0    1  2   3   4   id  product_20  product_10     price_20  \
0    625  807  0  53   8  625        20.0        30.0  2610.622839   
1    363  288  1   0  10  363         NaN         NaN          NaN   
2    869  982  0  31  10  869         NaN         NaN          NaN   
3    228  479  1  46   9  228         NaN         NaN          NaN   
4    980  851  1  14   3  980         NaN         NaN          NaN   
..   ...  ... ..  ..  ..  ...         ...         ...          ...   
995    1  890  1  72   5    1         NaN         NaN          NaN   
996  971  925  1  59   6  971         NaN         NaN          NaN   
997  536  721  1  28  10  536         NaN         NaN          NaN   
998  929   86  1  58  10  929         NaN         NaN          NaN   
999  803  113  1  42   9  803         NaN         NaN          NaN   

         price_21  quantity_20  quantity_21      amount_20      amount_21  \
0    20672.168459           80           47  208849.827158  971591.917564   
1             NaN           18           39            NaN            NaN   
2             NaN           24           63            NaN            NaN   
3             NaN           23           17            NaN            NaN   
4             NaN           62           14            NaN            NaN   
..            ...          ...          ...            ...            ...   
995           NaN           39           18            NaN            NaN   
996           NaN           29           39            NaN            NaN   
997           NaN            2           76            NaN            NaN   
998           NaN           61           89            NaN            NaN   
999           NaN           94           95            NaN            NaN   

             sales  
0    762742.090406  
1              NaN  
2              NaN  
3              NaN  
4              NaN  
..             ...  
995            NaN  
996            NaN  
997            NaN  
998            NaN  
999            NaN  

[1000 rows x 15 columns]

In [7]:
del ddf1['id']  # id열 삭제

In [8]:
ddf1 # 열삭제 확인

0    1  2   3   4  product_20  product_10     price_20      price_21  \
0    625  807  0  53   8        20.0        30.0  2610.622839  20672.168459   
1    363  288  1   0  10         NaN         NaN          NaN           NaN   
2    869  982  0  31  10         NaN         NaN          NaN           NaN   
3    228  479  1  46   9         NaN         NaN          NaN           NaN   
4    980  851  1  14   3         NaN         NaN          NaN           NaN   
..   ...  ... ..  ..  ..         ...         ...          ...           ...   
995    1  890  1  72   5         NaN         NaN          NaN           NaN   
996  971  925  1  59   6         NaN         NaN          NaN           NaN   
997  536  721  1  28  10         NaN         NaN          NaN           NaN   
998  929   86  1  58  10         NaN         NaN          NaN           NaN   
999  803  113  1  42   9         NaN         NaN          NaN           NaN   

     quantity_20  quantity_21      amount_20      amount_21          sales  
0             80           47  208849.827158  971591.917564  762742.090406  
1             18           39            NaN            NaN            NaN  
2             24           63            NaN            NaN            NaN  
3             23           17            NaN            NaN            NaN  
4             62           14            NaN            NaN            NaN  
..           ...          ...            ...            ...            ...  
995           39           18            NaN            NaN            NaN  
996           29           39            NaN            NaN            NaN  
997            2           76            NaN            NaN            NaN  
998           61           89            NaN            NaN            NaN  
999           94           95            NaN            NaN            NaN  

[1000 rows x 14 columns]

In [9]:
ddf1.rename(columns = {0:'id', 1:'cusno', 2:'gender',3:'age',4:'region'}, inplace= True) #열이름재설정
ddf1

id  cusno  gender  age  region  product_20  product_10     price_20  \
0    625    807       0   53       8        20.0        30.0  2610.622839   
1    363    288       1    0      10         NaN         NaN          NaN   
2    869    982       0   31      10         NaN         NaN          NaN   
3    228    479       1   46       9         NaN         NaN          NaN   
4    980    851       1   14       3         NaN         NaN          NaN   
..   ...    ...     ...  ...     ...         ...         ...          ...   
995    1    890       1   72       5         NaN         NaN          NaN   
996  971    925       1   59       6         NaN         NaN          NaN   
997  536    721       1   28      10         NaN         NaN          NaN   
998  929     86       1   58      10         NaN         NaN          NaN   
999  803    113       1   42       9         NaN         NaN          NaN   

         price_21  quantity_20  quantity_21      amount_20      amount_21  \
0    20672.168459           80           47  208849.827158  971591.917564   
1             NaN           18           39            NaN            NaN   
2             NaN           24           63            NaN            NaN   
3             NaN           23           17            NaN            NaN   
4             NaN           62           14            NaN            NaN   
..            ...          ...          ...            ...            ...   
995           NaN           39           18            NaN            NaN   
996           NaN           29           39            NaN            NaN   
997           NaN            2           76            NaN            NaN   
998           NaN           61           89            NaN            NaN   
999           NaN           94           95            NaN            NaN   

             sales  
0    762742.090406  
1              NaN  
2              NaN  
3              NaN  
4              NaN  
..             ...  
995            NaN  
996            NaN  
997            NaN  
998            NaN  
999            NaN  

[1000 rows x 14 columns]

In [ ]:
# 무얼할지?
- 세번째
나이대별 구매금액, 
성별별 거래량
지역(region)별 생산품(prod) 판매량
생산품별(product) 주요 나이/성별 (행 열 바꿔서보기)
거래량이 가장 많은 상품의 주고객층
연간 거래량 비주얼라이징 (plot)
상관관계 확인(df.corr())
제언 > 주요타깃 설정 및 공략
     > 유동적으로 많이 팔린 생산품 생산량 증가, 덜팔리는 상품 생산 감소

In [ ]:
#### Q2. df를 수정하여 3가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요
* 배운거 어떻게든 써서 
* 구매 데이터 생성
* 그룹핑등등 사용
* 피벗으로 잘 됐는지 확인?
#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.
* 분석에는 인덱스를 다른거 뽑아서 사용가능
* 판매율, 고정층, 연령층, 제품가격별, 물량 등등으로 분류해서 확인
* 의미있는 값으로 방향제시 혹은 결과 도출
* 의도한 목표가 잘 됐는지 확인

In [ ]:
id, cusno, gender, age, region
product price quantity amount sales

In [ ]:
- 첫번째 데이터프레임
id, cusno, gender, age, region

In [ ]:
- 두번째 데이터프레임 # 실패?
id, product price quantity amount sales

In [ ]:
# 함수로 넣어야하는지?
def sales :
    if amount_21 - amount_20 > 0 :
        return 1
    elif amount_21 - amount_20 < 0 :
        return 0
    else :
        break
        