In [2]:
import numpy as np

## 데이터와 행렬
- 스칼라 : 숫자 하나만으로 이루어진 데이터
- 벡터 : 여러 숫자가 특정한 순서대로 모여 있는 것을 의미. 하나의 벡터를 이루는 데이터 수가 n개이면 n-차원 벡터라고 함
- 열벡터는 열의 수가 1인 행렬
- 하나의 데이터 레코드를 단독으로 벡터로 나타낼 때는 하나의 열로 나타내고 복수의 데이터 레코드 집합을 행렬로 나타낼 때는 하나의 데이터 레코드가 하나의 행으로 표기하는 것은 데이터 분석에서 일반적인 관례
- 스칼라와 벡터도 수학적으로는 행렬에 속한다.
- 스칼라는 열과 행의 수가 각각 1인 행렬이고 벡터는 열의 수가 1인 행렬이다.


### Python Numpy 선형대수
```
단위행렬 (Unit matrix): np.eye(n)
대각행렬 (Diagonal matrix): np.diag(x)
내적 (Dot product, Inner product): np.dot(a, b)
대각합 (Trace): np.trace(x)
행렬식 (Matrix Determinant): np.linalg.det(x)
역행렬 (Inverse of a matrix): np.linalg.inv(x)
고유값 (Eigenvalue), 고유벡터 (Eigenvector): w, v = np.linalg.eig(x)
특이값 분해 (Singular Value Decomposition): u, s, vh = np.linalg.svd(A)
```
https://rfriend.tistory.com/380


<img src = '내적.jpg' STYLE = 'width:1000px;'>

벡터 a를 벡터 b와 같은 방향의 성분과 그렇지 않은 성분으로 분해한다고 할 때 $|a|cosθ$의 길이는 벡터 b와 같은 방향의 성분 길이와 같다.  

벡터 a와 b의 내적은 벡터 b의 길이와 벡터 a에서 벡터 b와 같은 방향의 성분 길이를 곱한 것이다.

- 행렬 내적은 행렬 곱이며 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능
- 행렬 내적의 특성으로 왼쪽 행렬의 열개수와 오른쪽 행렬의 행개수가 동일해야 내적 연산 가능


##### 과제 1013_1
- 상기 각 항목에 대한 예제를 풀어보기

In [3]:
# 단위행렬 (=항등행렬)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 대각행렬
np.diag(np.arange(1,5))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
# 내적
a = np.arange(1,5).reshape(2,2)
print(a)
np.dot(a,a)

[[1 2]
 [3 4]]


array([[ 7, 10],
       [15, 22]])

In [18]:
# 대각합
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.diag(a)

array([1, 5, 9])

In [23]:
np.trace(a)

15

In [24]:
# 대각합(3차원)
a= np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
np.trace(a)

array([6, 8])

In [41]:
# 행렬식 : 역행렬 존재여부 확인 >> 0이면 역행렬 X
a = np.arange(2,6).reshape(2,2)
a

array([[2, 3],
       [4, 5]])

In [42]:
np.linalg.det(a)

-2.0

In [43]:
# 역행렬
b = np.linalg.inv(a)
b

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [44]:
np.dot(a,b)

array([[1., 0.],
       [0., 1.]])

In [56]:
# 고유값, 고유벡터
a = np.array([[1,3],[3,7]])
w, v = np.linalg.eig(a)
w

array([-0.24264069,  8.24264069])

In [57]:
v

array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]])

In [58]:
np.dot(w,v)

array([ 3.37849279, -7.52235245])

In [61]:
# 특이값 분해 (정방행렬이 아닌경우)
a= np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
u, s, vh = np.linalg.svd(a)

In [64]:
u

array([[-0.3863177 ,  0.92236578],
       [-0.92236578, -0.3863177 ]])

In [65]:
s

array([9.508032  , 0.77286964])

In [66]:
vh

array([[-0.42866713, -0.56630692, -0.7039467 ],
       [-0.80596391, -0.11238241,  0.58119908],
       [ 0.40824829, -0.81649658,  0.40824829]])